/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Announcement = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'date' : Time,
  'description' : IDL.Text,
});
export const Event = IDL.Record({
  'title' : IDL.Text,
  'date' : Time,
  'time' : IDL.Text,
  'location' : IDL.Text,
});
export const SchoolInfo = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'principalName' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'addAcademicProgram' : IDL.Func([IDL.Text], [], []),
  'addAnnouncement' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, Time], [], []),
  'addEvent' : IDL.Func([IDL.Text, IDL.Text, Time, IDL.Text, IDL.Text], [], []),
  'getAcademicPrograms' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getAnnouncement' : IDL.Func([IDL.Text], [Announcement], ['query']),
  'getEvent' : IDL.Func([IDL.Text], [Event], ['query']),
  'getSchoolInfo' : IDL.Func([], [SchoolInfo], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Announcement = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'date' : Time,
    'description' : IDL.Text,
  });
  const Event = IDL.Record({
    'title' : IDL.Text,
    'date' : Time,
    'time' : IDL.Text,
    'location' : IDL.Text,
  });
  const SchoolInfo = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'principalName' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'addAcademicProgram' : IDL.Func([IDL.Text], [], []),
    'addAnnouncement' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, Time], [], []),
    'addEvent' : IDL.Func(
        [IDL.Text, IDL.Text, Time, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'getAcademicPrograms' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getAnnouncement' : IDL.Func([IDL.Text], [Announcement], ['query']),
    'getEvent' : IDL.Func([IDL.Text], [Event], ['query']),
    'getSchoolInfo' : IDL.Func([], [SchoolInfo], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };