/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Announcement {
  'id' : string,
  'title' : string,
  'date' : Time,
  'description' : string,
}
export interface Event {
  'title' : string,
  'date' : Time,
  'time' : string,
  'location' : string,
}
export interface SchoolInfo {
  'name' : string,
  'email' : string,
  'address' : string,
  'principalName' : string,
  'phone' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'addAcademicProgram' : ActorMethod<[string], undefined>,
  'addAnnouncement' : ActorMethod<[string, string, string, Time], undefined>,
  'addEvent' : ActorMethod<[string, string, Time, string, string], undefined>,
  'getAcademicPrograms' : ActorMethod<[], Array<string>>,
  'getAllAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getAllEvents' : ActorMethod<[], Array<Event>>,
  'getAnnouncement' : ActorMethod<[string], Announcement>,
  'getEvent' : ActorMethod<[string], Event>,
  'getSchoolInfo' : ActorMethod<[], SchoolInfo>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];